name: flutter_firebase
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.19.4
  firebase_database: ^10.2.3
  google_sign_in: ^6.1.4
  firebase_core: ^2.30.1
  get: ^4.6.5
  flutter_launcher_icons: ^0.13.1
  
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  percent_indicator: ^4.2.3
  animations: ^2.0.7
  flutter_svg: ^2.0.7
  animated_background: ^2.0.0
  rainbow_color: ^2.0.1
  sleek_circular_slider: ^2.0.1
  chart_sparkline: ^1.0.15+1
  weather: ^3.1.1
  cloud_firestore: ^4.14.0
  
  syncfusion_flutter_charts: ^25.1.40

  dropdown_button2: ^2.3.9

  buttons_tabbar: ^1.3.8
  icons_plus: ^5.0.0
  shared_preferences: ^2.2.3

  awesome_notifications: ^0.8.2
  awesome_notifications_core: ^0.9.0
  
  flutter_background_service: ^5.0.5
  device_info_plus: ^10.1.0
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#e4eff1"
    theme_color: "#e4eff1"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"


flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
 
  uses-material-design: true
  